server:
  port: 8080
  ssl:
    enabled: true
    key-store:
    key-store-type:
    key-password:
    trust-store:
    trust-store-password:
    key-alias:

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
            allowedHeaders:
            allowedMethods:
      httpclient: # 타임아웃 설정
        connect-timeout: 10000
        response-timeout: 10s
#      default-filters: # 디폴트 필터
#        - name: GlobalFilter
      routes:
        - id: SlackBot Domain
          uri:
          predicates:
            -
          filters:
            - GlobalFilter

#        - id: User Domain Sign Up, Login  # 유저 로그인, 회원가입은 JWT 토큰 인증과정 없음.
#          uri: http://3.39.184.27:8080/
#          predicates:
#            - Method=POST
#            - Path=/user/login,/user/account
#          filters:
#            - GlobalFilter

        - id: User Domain
          uri:
          predicates:
            - Path=/user/**
          filters:
            - GlobalFilter
#          filters:
#            - JwtAuthenticationFilter

        - id: Chatting Domain
          uri:
          predicates:
            - Path=/chatting/**
          filters:
            - GlobalFilter

        - id: News Domain
          uri:
          predicates:
            - Path=/news/**
          filters:
            - GlobalFilter

        - id: Data Lake Domain
          uri:
          predicates:
            - Path=/dataLake/**
          filters:
            - GlobalFilter

        - id: Drawing Image Domain
          uri:
          predicates:
            - Path=/drawing/**
          filters:
            - GlobalFilter

jwt:
  secret: